version: 0.2

phases:
  build:
    commands:
      - echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - echo ===============Railsデプロイ開始===============
      - ssh -o StrictHostKeyChecking=no -i private_key ec2-user@$PUBLIC_IP -tt "cd $APP_NAME &&
        git pull origin $BRANCH &&
        ~/.rbenv/shims/bundle install &&
        ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production &&
        ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production &&
        ls tmp/pids &&
        if [[ -e tmp/pids/puma.pid ]];then sudo kill $(cat tmp/pids/puma.pid); echo kill puma process;fi &&
        ~/.rbenv/shims/rails s -e production"
    finally:
      - echo ===============Railsデプロイ完了===============
