version: '3.9' 
services:
  api:
    build: 
      context: .
      args:
        WORKDIR: $WORKDIR
    volumes:
      - .:/$WORKDIR
      - public:/$WORKDIR/public
      - tmp:/$WORKDIR/tmp
    stdin_open: true
    tty: true
  nginx:
    build:
      args:
        ENVIRONMENT: prd
        WORKDIR: $WORKDIR  
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/$WORKDIR/public
      - tmp:/$WORKDIR/tmp
    ports:
      - "80:80"
    depends_on:
      - api
volumes:
  mysql-data:
    driver: local
  tmp:
  public:
