version: '3.9' 
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: 
      context: .
      args:
        WORKDIR: $WORKDIR
    volumes:
      - .:/$WORKDIR
      - public:/$WORKDIR/public
      - tmp:/$WORKDIR/tmp
    depends_on:
      - db
    stdin_open: true
    tty: true
  nginx:
    build:
      args:
        ENVIRONMENT: local
        WORKDIR: $WORKDIR  
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/$WORKDIR/public
      - tmp:/$WORKDIR/tmp
    ports:
      - "80:80"
    depends_on:
      - api
volumes:
  mysql-data:
    driver: local
  tmp:
  public:
